using Unity.VisualScripting;
using UnityEngine;
using System.Collections;

public class Da単oAJefe : MonoBehaviour
{
    [SerializeField] private float da単o = 10;
    [SerializeField] private Animator animator;

    void Start()
    {
        animator = GetComponent<Animator>();

    }

    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            GameObject jefeEnemy = GameObject.FindWithTag("Jefe");

            if (jefeEnemy != null)
            {
                jefeEnemy.GetComponent<JefeArrow>().TomarDa単o(da単o);
                animator.SetTrigger("Entro");

            }

        }

    }

    void Destruirse()
    {
        gameObject.SetActive(false);
    }


}
